# Generated by Django 5.2.7 on 2025-10-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('bigcommerce', 'BigCommerce'), ('custom', 'Custom')], max_length=20)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=32)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['domain'], name='stores_domain_096cf8_idx'), models.Index(fields=['api_key'], name='stores_api_key_4075f8_idx'), models.Index(fields=['is_active'], name='stores_is_acti_89b637_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='stores.store')),
            ],
            options={
                'db_table': 'store_api_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
