# Generated by Django 5.2.7 on 2025-10-27 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteractionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('page_views', models.IntegerField(default=0)),
                ('products_viewed', models.IntegerField(default=0)),
                ('unique_products_viewed', models.IntegerField(default=0)),
                ('total_interactions', models.IntegerField(default=0)),
                ('landing_page', models.URLField(blank=True, max_length=1000)),
                ('exit_page', models.URLField(blank=True, max_length=1000)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('added_to_cart', models.BooleanField(default=False)),
                ('purchased', models.BooleanField(default=False)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_sessions', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions_sessions', to='users.user')),
            ],
            options={
                'db_table': 'user_interaction_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('detail_view', 'Detail View'), ('cart_add', 'Add to Cart'), ('cart_remove', 'Remove from Cart'), ('wishlist_add', 'Add to Wishlist'), ('wishlist_remove', 'Remove from Wishlist'), ('purchase', 'Purchase'), ('review', 'Review'), ('share', 'Share'), ('like', 'Like'), ('dislike', 'Dislike'), ('search', 'Search'), ('filter', 'Filter')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('weight', models.FloatField(default=1.0)),
                ('page_url', models.URLField(blank=True, max_length=1000)),
                ('page_title', models.CharField(blank=True, max_length=255)),
                ('referrer_url', models.URLField(blank=True, max_length=1000)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('screen_resolution', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=10)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_category', models.CharField(blank=True, max_length=255)),
                ('search_query', models.CharField(blank=True, max_length=255)),
                ('search_results_count', models.IntegerField(blank=True, null=True)),
                ('search_position', models.IntegerField(blank=True, null=True)),
                ('time_on_page', models.IntegerField(default=0)),
                ('scroll_depth', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='stores.store')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='users.user')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='interactions.userinteractionsession')),
            ],
            options={
                'db_table': 'interactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('test_type', models.CharField(choices=[('recommendation_algorithm', 'Recommendation Algorithm'), ('ui_placement', 'UI Placement'), ('personalization', 'Personalization Level')], max_length=50)),
                ('variants', models.JSONField(default=dict)),
                ('traffic_percentage', models.FloatField(default=100.0)),
                ('variant_weights', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('primary_metric', models.CharField(default='conversion_rate', max_length=100)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_tests', to='stores.store')),
            ],
            options={
                'db_table': 'ab_tests',
                'indexes': [models.Index(fields=['store', 'status'], name='ab_tests_store_i_33c1d1_idx'), models.Index(fields=['store', 'start_date'], name='ab_tests_store_i_45b551_idx')],
            },
        ),
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('event_data', models.JSONField(default=dict)),
                ('user_id', models.CharField(blank=True, max_length=255)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('product_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_events', to='stores.store')),
            ],
            options={
                'db_table': 'interaction_events',
                'indexes': [models.Index(fields=['store', 'created_at'], name='interaction_store_i_95c3e1_idx'), models.Index(fields=['store', 'processed'], name='interaction_store_i_968a18_idx'), models.Index(fields=['session_id'], name='interaction_session_79aa6f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_views', models.IntegerField(default=0)),
                ('unique_views', models.IntegerField(default=0)),
                ('detail_views', models.IntegerField(default=0)),
                ('avg_time_on_page', models.FloatField(default=0.0)),
                ('cart_adds', models.IntegerField(default=0)),
                ('purchases', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_analytics', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to='stores.store')),
            ],
            options={
                'db_table': 'product_views',
                'indexes': [models.Index(fields=['store', 'date'], name='product_vie_store_i_b8809a_idx'), models.Index(fields=['product', 'date'], name='product_vie_product_4b2e78_idx')],
                'unique_together': {('store', 'product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_interactions', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('total_purchases', models.IntegerField(default=0)),
                ('total_cart_adds', models.IntegerField(default=0)),
                ('avg_session_duration', models.FloatField(default=0.0)),
                ('avg_time_between_sessions', models.FloatField(default=0.0)),
                ('last_active_date', models.DateTimeField(blank=True, null=True)),
                ('preferred_categories', models.JSONField(blank=True, default=dict)),
                ('preferred_brands', models.JSONField(blank=True, default=dict)),
                ('price_preference', models.JSONField(blank=True, default=dict)),
                ('browsing_pattern', models.CharField(blank=True, max_length=50)),
                ('purchase_frequency', models.CharField(blank=True, max_length=50)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('feature_vector', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_profile', to='users.user')),
            ],
            options={
                'db_table': 'user_behavior_profiles',
                'indexes': [models.Index(fields=['store', 'user'], name='user_behavi_store_i_0e90da_idx')],
                'unique_together': {('store', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='userinteractionsession',
            index=models.Index(fields=['store', 'session_id'], name='user_intera_store_i_b7a75d_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteractionsession',
            index=models.Index(fields=['store', 'start_time'], name='user_intera_store_i_a7dadc_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteractionsession',
            index=models.Index(fields=['session_id'], name='user_intera_session_a8b8f3_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteractionsession',
            index=models.Index(fields=['start_time'], name='user_intera_start_t_5342a2_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteractionsession',
            index=models.Index(fields=['user', 'start_time'], name='user_intera_user_id_e3a1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['store', 'user', 'interaction_type'], name='interaction_store_i_64c477_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['store', 'product', 'interaction_type'], name='interaction_store_i_da8bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['store', 'created_at'], name='interaction_store_i_6f77ea_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['user', 'created_at'], name='interaction_user_id_beb693_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['product', 'created_at'], name='interaction_product_e909af_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['interaction_type', 'created_at'], name='interaction_interac_c2785c_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['session', 'created_at'], name='interaction_session_677570_idx'),
        ),
    ]
