# Generated by Django 5.2.7 on 2025-10-27 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('user_profile', models.JSONField(blank=True, default=dict)),
                ('total_interactions', models.IntegerField(default=0)),
                ('total_purchases', models.IntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('last_purchase', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='stores.store')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(max_length=100)),
                ('preference_value', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=1.0)),
                ('source', models.CharField(default='inferred', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='users.user')),
            ],
            options={
                'db_table': 'user_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('page_views', models.IntegerField(default=0)),
                ('products_viewed', models.IntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('landing_page', models.URLField(blank=True, max_length=1000)),
                ('exit_page', models.URLField(blank=True, max_length=1000)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to='users.user')),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['store', 'user_id'], name='users_store_i_b4f52e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['store', 'email'], name='users_store_i_949cb4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['store', 'session_id'], name='users_store_i_b3bc4f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_seen'], name='users_first_s_90fe5c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['last_seen'], name='users_last_se_f59089_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['total_interactions'], name='users_total_i_932ba5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('store', 'user_id')},
        ),
        migrations.AddIndex(
            model_name='userpreference',
            index=models.Index(fields=['user', 'preference_type'], name='user_prefer_user_id_98103b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('user', 'preference_type', 'preference_value')},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['store', 'user', 'start_time'], name='user_sessio_store_i_d213c1_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_id'], name='user_sessio_session_e62ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['start_time'], name='user_sessio_start_t_f82870_idx'),
        ),
    ]
