# Generated by Django 5.2.7 on 2025-11-02 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('collaborative', 'Collaborative Filtering'), ('content', 'Content-Based'), ('hybrid', 'Hybrid')], max_length=50)),
                ('version', models.CharField(max_length=50)),
                ('model_file', models.FileField(upload_to='ml_models/')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.store')),
            ],
            options={
                'unique_together': {('store', 'name', 'version')},
            },
        ),
    ]
